/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kathra.harbor.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * The components overview of the image.
 */
@ApiModel(description = "The components overview of the image.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-05T17:56:47.048Z")
public class DetailedTagScanOverviewComponents {
  @SerializedName("total")
  private Integer total = null;

  @SerializedName("summary")
  private List<ComponentOverviewEntry> summary = null;

  public DetailedTagScanOverviewComponents total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Total number of the components in this image.
   * @return total
  **/
  @ApiModelProperty(value = "Total number of the components in this image.")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  public DetailedTagScanOverviewComponents summary(List<ComponentOverviewEntry> summary) {
    this.summary = summary;
    return this;
  }

  public DetailedTagScanOverviewComponents addSummaryItem(ComponentOverviewEntry summaryItem) {
    if (this.summary == null) {
      this.summary = new ArrayList<ComponentOverviewEntry>();
    }
    this.summary.add(summaryItem);
    return this;
  }

   /**
   * List of number of components of different severities.
   * @return summary
  **/
  @ApiModelProperty(value = "List of number of components of different severities.")
  public List<ComponentOverviewEntry> getSummary() {
    return summary;
  }

  public void setSummary(List<ComponentOverviewEntry> summary) {
    this.summary = summary;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedTagScanOverviewComponents detailedTagScanOverviewComponents = (DetailedTagScanOverviewComponents) o;
    return Objects.equals(this.total, detailedTagScanOverviewComponents.total) &&
        Objects.equals(this.summary, detailedTagScanOverviewComponents.summary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, summary);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedTagScanOverviewComponents {\n");
    
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

