/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kathra.harbor.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * ProjectReq
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-05T17:56:47.048Z")
public class ProjectReq {
  @SerializedName("project_name")
  private String projectName = null;

  @SerializedName("metadata")
  private ProjectMetadata metadata = null;

  public ProjectReq projectName(String projectName) {
    this.projectName = projectName;
    return this;
  }

   /**
   * The name of the project.
   * @return projectName
  **/
  @ApiModelProperty(value = "The name of the project.")
  public String getProjectName() {
    return projectName;
  }

  public void setProjectName(String projectName) {
    this.projectName = projectName;
  }

  public ProjectReq metadata(ProjectMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * The metadata of the project.
   * @return metadata
  **/
  @ApiModelProperty(value = "The metadata of the project.")
  public ProjectMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(ProjectMetadata metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectReq projectReq = (ProjectReq) o;
    return Objects.equals(this.projectName, projectReq.projectName) &&
        Objects.equals(this.metadata, projectReq.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectName, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectReq {\n");
    
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

