---
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "${DESC}"
  labels:
    product: "${PRODUCT_NAME}"
    app: "${SERVICE_NAME}"
  name: "${SERVICE_NAME}-${IMPL_NAME}"
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: "${SERVICE_NAME}-${IMPL_NAME}"
    labels:
      product: "${PRODUCT_NAME}"
      app: "${SERVICE_NAME}"
      impl: "${IMPL_NAME}"
  spec:
    replicas: '1'
    template:
      metadata:
        labels:
          product: "${PRODUCT_NAME}"
          app: "${SERVICE_NAME}"
          impl: "${IMPL_NAME}"
      spec:
        containers:
        - name: "${SERVICE_NAME}-${IMPL_NAME}"
          image: "${IMAGE_NAME}"
          ports:
          - name: web
            containerPort: ${PORT}
            protocol: TCP
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: RESOURCE_MANAGER_URL
              valueFrom:
                configMapKeyRef:
                  key: RESOURCE_MANAGER_URL
                  name: binaryrepositorymanager-config
            - name: HARBOR_URL
              valueFrom:
                configMapKeyRef:
                  key: HARBOR_URL
                  name: binaryrepositorymanager-config
            - name: HARBOR_USERNAME
              valueFrom:
                secretKeyRef:
                  key: HARBOR_USERNAME
                  name: binaryrepositorymanager-secret
            - name: HARBOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: HARBOR_PASSWORD
                  name: binaryrepositorymanager-secret
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  key: USERNAME
                  name: binaryrepositorymanager-secret
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: binaryrepositorymanager-secret
            - name: KEYCLOAK_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_AUTH_URL
                  name: keycloak-config
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_REALM
                  name: keycloak-config
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_CLIENT_ID
                  name: kathra-keycloak-secret
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_CLIENT_SECRET
                  name: kathra-keycloak-secret
          resources:
            limits:
              cpu: "${RESOURCES_CPU_MAX}"
              memory: "${RESOURCES_MEM_MAX}"
            requests:
              cpu: "${RESOURCES_CPU_MIN}"
              memory: "${RESOURCES_MEM_MIN}"
- kind: Service
  apiVersion: v1
  metadata:
    name: "${SERVICE_NAME}"
    labels:
      product: "${PRODUCT_NAME}"
      app: "${SERVICE_NAME}"
      expose: true
  spec:
    ports:
    - protocol: TCP
      port: 80
      targetPort: ${PORT}
    selector:
      product: "${PRODUCT_NAME}"
      app: "${SERVICE_NAME}"
    type: ClusterIP
    sessionAffinity: None
